image: node:latest

cache:
  paths:
    - node_modules/

pages:
  only:
    - publish
  script:
    - npm install
    # Fix URL since GitLab hosts at a subdomain
    - sed -i 's|/web_modules/|/stayknit/web_modules/|' .babelrc.json
    - npm run setup
    - npm run ssr
    - mv serve public
  artifacts:
    paths:
      - public/
